name: Validate Java e2e
on:
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  setup-java-major-versions:
    name: ${{ matrix.distribution }} ${{ matrix.version }} (jdk-x64) - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        distribution: ['adoptium', 'zulu']
        version: ['8', '11', '14', '15']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup-java
        uses: ./
        id: setup-java
        with:
          java-version: ${{ matrix.version }}
          java-package: 'jdk'
          distribution: ${{ matrix.distribution }}
      - name: Verify Java
        run: bash __tests__/verify-java.sh "${{ matrix.version }}" "${{ steps.setup-java.outputs.path }}"
        shell: bash


  setup-java-major-minor-versions:
    name: ${{ matrix.distribution }} ${{ matrix.java }} (jdk-x64) - ${{ matrix.os }}
    needs: setup-java-major-versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        distribution: ['adoptium', 'zulu']
        java:
        - '8.0'
        - '8.0.282'
        - '11.0'
        - '11.0.10'
        - '15.0'
        exclude:
          - os: windows-latest
            distribution: 'zulu'
            java: '8.0.282'
          - os: windows-latest
            distribution: 'zulu'
            java: '11.0.10'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup-java
        uses: ./
        with:
          java-version: ${{ matrix.java }}
          java-package: jdk
          distribution: ${{ matrix.distribution }}
      - name: Java version
        run: java -version

  setup-java-ea-versions:
    name: ${{ matrix.distribution }} ${{ matrix.java }} (jdk-x64) - ${{ matrix.os }}
    needs: setup-java-major-minor-versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        distribution: ['adoptium', 'zulu']
        java:
        - '15-ea'
        - '15.0-ea'
        - '15.0.0-ea'
        exclude:
          - os: windows-latest
            distribution: 'zulu'
            java: '15.0.0-ea'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup-java
        uses: ./
        with:
          java-version: ${{ matrix.java }}
          java-package: jdk
          distribution: ${{ matrix.distribution }}
      - name: Java version
        run: java -version

  setup-java-custom-package-type:
    name: ${{ matrix.distribution }} ${{ matrix.java }} (${{ matrix.java-package }}-x64) - ${{ matrix.os }}
    needs: setup-java-major-minor-versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        distribution: ['adoptium', 'zulu']
        java-package: ['jre']
        java:
        - '8'
        - '8.0.282'
        - '11'
        - '11.0.10'
        - '15.0'
        exclude:
          - os: windows-latest
            distribution: 'zulu'
            java-package: 'jre'
            java: '8.0.282'
          - os: windows-latest
            java-package: 'jre'
            distribution: 'zulu'
            java: '11.0.10'
        include:
          - distribution: 'zulu'
            java-package: jre+fx
            java: '8'
            os: ubuntu-latest
          - distribution: 'zulu'
            java-package: jdk+fx
            java: '8'
            os: ubuntu-latest
          - distribution: 'zulu'
            java-package: jdk+fx
            java: '8.0.242'
            os: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup-java
        uses: ./
        with:
          java-version: ${{ matrix.java }}
          java-package: ${{ matrix.java-package }}
          distribution: ${{ matrix.distribution }}
      - name: Java version
        run: java -version

  setup-java-custom-architecture:
    name: ${{ matrix.distribution }} ${{ matrix.java }} (jdk-x86) - ${{ matrix.os }}
    needs: setup-java-major-minor-versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Only Zulu provides x86 arch for now and only for windows / ubuntu
        os: [windows-latest, ubuntu-latest]
        distribution: ['zulu']
        java:
        - '8'
        - '11'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup-java
        uses: ./
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
          architecture: x86
      - name: Java version
        run: java -version